### PR TITLE
Working on the modern version of bindable

### PR DESCRIPTION
**Pull request by mkitt**
Did some more preliminary testing around porting bindable to native JavaScript and porting our existing mocha tests over from the utensils repository. Couple of issues:
1. One failing test, not totally sure whats going on there.
2. ~~The `document.querySelector` looking at `data-bindable` borks on IE 8 and 9~~

~~Not sure if it's worth it to keep going down this rabbit hole, but wanted to put this out there for anyone that might be interested.~~

/cc @cacheflowe, @jedschneider, @jejacks0n, @gvarela, @jayzes

### CODE REVIEW

**Comment by mkitt** [comment]
Forget to put the doctype into the test file which was forcing IE8/9 into quirks mode. Rookie mistake. Anyhow this now works down to IE8.

**Comment by jejacks0n** [comment]
Sweet!

**Comment by jedschneider** [comment]
so its good to merge? whats next, adding a hook for using jquery if needed?

**Comment by jejacks0n** [comment]
I think the only jQuery hook that would be needed is in the instantiation of the bindable components -- eg. passing it a jquery object instead of the element directly if $ is defined.

**Comment by jedschneider** [comment]
I see, so we would leave it up to the class to take that element and do what it wants with it:

``` coffeescript
class MyComponent
  constructor: (el)->
    @el = $(el)

Bindable.register 'my-component', MyComponent
```

**Comment by mkitt** [comment]
I still need to get that failing test to pass. Not sure if someone wants to take a look. I just ported the tests we had from utensils over and that is one that isn't quite passing from the original suite.

Also, not sure if we would want to have a jQuery specific one, which would work for IE7

**Comment by jejacks0n** [comment]
@jedschneider that's what I was saying we could do as a jquery tie in.  In bindable (psuedo code):

```
if (window.$) el = $(el)
new MyComponent(el)
```

**Comment by jedschneider** [comment]
ah, got it. @mkitt I'll take a look at the test. try to get that resolved by monday.

**Comment by mkitt** [comment]
Yeah, if we send it out from bindable cast as a jQuery object, I think that works better. I believe this what Angular does with jQlite as well.

**Comment by mkitt** [comment]
Cool thanks @jedschneider, I'll probably add some more tests too just to help my OCD.

**Comment by jedschneider** [comment]
maybe it would be nice to send the i don't know what you'd really call it, the function wrapper/object constructor, into Bindable at the same time as we do the bindall, the same way we inject the context and the data attribute. that way we are not making any demands on the dom function

``` coffeescript
new Bindable.bindAll $(document), 'bindable', $

# and in bindable
# where func is defined in the constructor if not provided... or maybe we dont cast it if nothing responds to $?

new MyCompoent(func(el))
```

something  like that?

**Comment by jedschneider** [comment]
maybe if func isn't defined we just have func return the el

``` javascript
elWrapper = function(func){ if (typeof(func) == 'function') return func else return function(el){ return el } }

// and in bindable
new MyComponent(elWrapper(el))
```

_not linted or even really correct im sure_

**Comment by jedschneider** [comment]
@mkitt with that spec fixed, i think we should just merge this and move forward with our other issues separately. what do you think?

**Comment by mkitt** [comment]
Agreed.

**Pull request merged**
